import win32api

MOUSEEVENTF_MOVE: int = 0x0001


class Config:
    def __init__(self):
        self.keys = (
            "shift",
            "x",
            "x2",
            "alt",
            "ctrl",
            "insert",
            "home",
            "page up",
            "delete",
            "end",
            "page down",
            "f1",
            "f2",
            "f3",
            "f4",
            "f5",
            "f6",
            "f7",
            "f8",
            "f9",
            "f10",
            "f11",
            "f12",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "up",
            "left",
            "down",
            "right",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "y",
            "z",
            "-",
            "=",
            "backspace",
            "tab",
            "[",
            "]",
            "caps lock",
            ";",
            "'",
            "enter",
            ",",
            ".",
            "/",
            "num lock",
            "*",
            "+",
            "scroll lock",
            "pause",
            "`",
        )
        self.MOUSEEVENTF_MOVE = MOUSEEVENTF_MOVE
        self.SCREEN_WIDTH = win32api.GetSystemMetrics(0)
        self.SCREEN_HEIGHT = win32api.GetSystemMetrics(1)
        self.BONE_INDICES = {
            "waist": 1,
            "spine_2": 4,
            "spine_1": 3,
            "neck": 6,
            "head": 7,
            "shoulder_right": 13,
            "arm_right": 14,
            "hand_left": 11,
            "shoulder_left": 9,
            "arm_left": 10,
            "hand_right": 15,
            "leg_left": 17,
            "knee_left": 18,
            "ankle_left": 19,
            "leg_right": 20,
            "knee_right": 21,
            "ankle_right": 22,
        }


config = Config()
